[35기 nhouse 조예슬] 카카오 로그인 api 작성
wecode-bootcamp-korea/35-2nd-nhouse-backend pull request #5
Opened 2022-08-03 15:26 UTC by eungang3

## :: 최근 작업 주제 (하나 이상의 주제를 선택해주세요.)
- [x] 기능 추가
- [ ] 리뷰 반영
- [ ] 리팩토링
- [ ] 버그 수정
- [ ] 컨벤션 수정

<br />

## :: 구현 목표
- 카카오 로그인 api로 내일의 집 로그인/회원가입 구현하기
- 회원가입 성공 시 "SIGNUP_SUCCESS" 메시지와 201 코드 반환
- 로그인 성공 시 "LOGIN_SUCCESS" 메시지와 200 코드 반환
- 인가 코드가 유효하지 않은 경우 "INVALID_AUTHORIZATION_CODE" 메시지와 401 코드 반환
- 키 에러가 나는 경우 "KEY_ERROR" 메시지와 400 코드 반환

<br />

## :: 구현 사항 설명 
1. 프론트에서 보내주는 인가 코드를 전달받음
2. 토큰을 발급하는 카카오 REST API에 django requests로 요청 보내고 카카오 토큰 응답받기
3. 유저 정보를 응답하는 카카오 REST API에 django requsts로 요청 보내고 유저 정보 응답받기
4. 유저 정보를 응답받으면 유저의 카카오 아이디가 DB에 있는지 확인
5. 유저의 카카오 아이디가 DB에 있으면 "LOGIN_SUCCESS" 메시지와 jwt 반환 
6. 유저의 카카오 아이디가 DB에 없으면 DB에 유저 정보 저장 후 "SIGNUP_SUCCESS" 메시지와 jwt 반환
 
<br />

## :: 성장 포인트 (해당 기능을 구현하며 고민했던 사항이나 새로 알게된 부분, 어려웠던 점 등을 작성합니다.)
- 공식 문서를 읽어보고 REST API를 사용해보았습니다.
   + 카카오 API의 인가 코드, 토큰, 서비스에서 발급하는 jwt 토큰의 역할과 차이점에 대해 알게 되었습니다.
      - 인가 코드는 내일의 집이 카카오의 유저 정보에 접근해도 된다는 증거입니다.
      - 카카오 토큰은 유저가 카카오에 로그인했다는 증거입니다.
      - 내일의 집에서 발급하는 jwt는 유저가 내일의 집에 로그인했다는 증거입니다.
  
    + 낯선 기술을 사용할 때 효율적으로 공부하는 방식에 대해 생각해보았습니다.
      - 우선 공식 문서를 읽습니다.
      - 모르는 단어나 이해가 가지 않는 부분은 리서치를 해서 제대로 이해합니다.
      - 그런 다음 공식 문서를 누군가에게 설명한다고 생각하고 내 언어로 정리해봅니다.
      - 이제 공부한 기술을 내 프로젝트의 어느 부분에 어떻게 적용할 지 글로 간단하게 정리해봅니다.
      - 구체적인 적용 방법을 모르겠으면 리서치를 합니다.
      - 코드를 작성합니다. 

- 인증, 인가의 개념에 대해 더 잘 이해하게 되었습니다.
   + 인증은 유저가 우리 서비스에 등록되었는지 확인하는 것입니다.
   + 인가는 현재 유저가 어딘가에 접근하려고 할 때 권한이 있는지 확인하는 것입니다.

- django의 requests 모듈을 사용해보았습니다.
   + requests 모듈을 사용하면 django에서 외부 REST API를 호출할 수 있음을 알게 되었습니다.
   + django에서 API를 호출할 때 요청 헤더와 바디에 어떻게 정보를 담아 보낼 수 있는지 배웠습니다.

<br />

## :: 기타 질문 및 특이 사항
- 없습니다.

2022-08-04 06:45 UTC, bigfanoftim commented
> 방금 unit test 세션을 들었는데, 이 PR도 unit test 작성 후 다시 올려야 하나요?

예슬님! PR은 언제든지 리뷰 원하시면 컨플릭트 해결 및 rebase 후 올려주시면 됩니다!
대신 해당 PR은 테스트 코드까지 올라왔을때 머지해드리겠습니다!

2022-08-04 06:49 UTC, eungang3 commented
@bigfanoftim 넵 감사합니다! 그럼 리뷰 먼저 부탁드릴게요!

2022-08-04 07:03 UTC, bigfanoftim requested changes

2022-08-04 07:03 UTC, bigfanoftim commented on users/views.py
> +            user, is_created = User.objects.get_or_create(kakao_id = kakao_id)
defaults 옵션을 사용해보시면 좋을 것 같아요.
그럼 수정된 코드에 맞춰서 아래 `is_created` 플래그 활용하는 부분도 수정하시면 됩니다!

2022-08-06 07:38 UTC, eungang3 commented on users/views.py
> +            user, is_created = User.objects.get_or_create(kakao_id = kakao_id)
수정했습니다!

2022-08-08 02:00 UTC, bigfanoftim approved these changes
LGTM 👍

2022-08-08 02:00 UTC, merged