[35기 nhouse 조예슬] Initial settings 수정
wecode-bootcamp-korea/35-2nd-nhouse-backend pull request #6
Opened 2022-08-04 09:51 UTC by enddl3224

## :: 최근 작업 주제 (하나 이상의 주제를 선택해주세요.)
- [x] 기능 추가
- [ ] 리뷰 반영
- [ ] 리팩토링
- [ ] 버그 수정
- [ ] 컨벤션 수정

<br />

## :: 구현 목표 (해당 브랜치에서 구현하고자 하는 하나의 목표를 설정합니다.)
- .gitignore의 CSV관련 파일을 추가했습니다.

<br />

## :: 구현 사항 설명 (작업한 내용을 상세하게 기록합니다.)

<br />

## :: 성장 포인트 (해당 기능을 구현하며 고민했던 사항이나 새로 알게된 부분, 어려웠던 점 등을 작성합니다.)

<br />

## :: 기타 질문 및 특이 사항

2022-08-04 10:58 UTC, bigfanoftim requested changes
gitignore만 수정된게 아니라 다른것들이 많이 올라왔는데 맞나요?

2022-08-04 13:50 UTC, bigfanoftim approved these changes

2022-08-05 00:59 UTC, eungang3 commented
@bigfanoftim .gitignore를 수정하기 전에 깜빡하고 main 브랜치를 merge하지 않아서 다른 파일까지 올라온 것 같습니다. PR 다시 만들어야 할까요?

2022-08-05 02:06 UTC, bigfanoftim commented
> @bigfanoftim
> 
> 1. .gitignore를 수정하기 전에 깜빡하고 main 브랜치를 merge하지 않아서 다른 파일까지 올라온 것 같습니다. PR 다시 만들어야 할까요?
> 2. 어제 난 conflict는 해결했습니다! conflict 해결 요청 라벨을 달아주셨는데 더 해결할 conflict가 있나요?

예슬님 죄송해요 ㅠㅠ conflict 해결 요청이 아니라 rebase 요청을 달았어야 했는데... ㅎㅎ rebase 하고 다시 푸시해주세요~
PR은 다시 만드실 필요는 없습니다. rebase만 해주세요~

2022-08-05 02:06 UTC, bigfanoftim commented
<img width="686" alt="image" src="https://user-images.githubusercontent.com/62135254/182986297-f5beea41-6f75-4e9e-b35c-f3d034e97dc6.png">

2022-08-05 05:19 UTC, closed without merging